export const ReactQueryKey = {
    Company: "Company",
    SupplierGroup: "SupplierGroup",
    Supplier: "Supplier",
    AccountVoucher: "AccountVoucher",
    TransactionTypes: "TransactionTypes",
    TransactionTypesActive: "TransactionTypesActive",
    Projects: "Projects",
    ProjectsActive: "ProjectsActive",
    Suppliers: "Suppliers",
    SuppliersActive: "SuppliersActive",
    PaymentMethodsActive: "PaymentMethodsActive",
    ChartOfAccountsActive: "ChartOfAccountsActive",
    CashFlowCategoriesActive: "CashFlowCategoriesActive",
    AccountCategoriesActive: "AccountCategoriesActive",
    AccountTypesActive: "AccountTypesActive",


    //-----------------------------------------------
    buyer: "buyer",
    brand: "brand",
    unit: "unit",
    style: "style",
    styleByBuyer: "styleByBuyer",
    po: "po",
    poByStyle: "poByStyle",
    fabric: "fabric",
    yarn: "yarn",
    yarnLot: "yarnLot",
    yarnCount: "yarnCount",
    yarnComposition: "yarnComposition",
    yarnType: "yarnType",
    Item: "item",
    fabricWorkOrder: "fabricWorkOrder",
    generalBlockFabricStatus: "generalBlockFabricStatus",
    material: "material",
    material_fabric: "material_fabric",
    material_yarn: "material_yarn",
    supplier: "supplier",
    country: "country",
    SwtMachineGroup: "SwtMachineGroup",
    SwtPlanningBoard: "SwtPlanningBoard",
    Employee: "Employee",
    floor: "floor",
    ItemType: "ItemType",
    LearningCurve: "LearningCurve",
    Buyer: "Buyer",
    Color: "Color",
    Size: "Size",
    CompensationClaim: "CompensationClaim",
    ClaimId: "ClaimId",
    PrintEmbProduction: "PrintEmbProduction",
    PrintEmbProductionOperation: "PrintEmbProductionOperation",
    PrintEmbProductionHour: "PrintEmbProductionHour",
    EmbMaterialReceive: "EmbMaterialReceive",
    FinishGoodValuation: "FinishGoodValuation",
};